//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapptesting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class authordata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public authordata()
        {
            this.bookdatas = new HashSet<bookdata>();
        }
    
        public int Author_ID { get; set; }
        [Required(ErrorMessage = "Enter date")]
        [Display(Name = "Created on")]
        public System.DateTime Created_Date { get; set; }
        [Required(ErrorMessage = "Book update date")]
        public System.DateTime Updated_Date { get; set; }
        [Required(ErrorMessage = "Manxey jeudai xa ra books publis vairakheko xa vaye ignore this")]
        public bool Is_Discontinued { get; set; }
        [Required(ErrorMessage = "Naya author ko name lekhnus")]
        public string Author_Name { get; set; }
        [Display(Name = "Author Name")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookdata> bookdatas { get; set; }
    }
}
