//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapptesting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bookdata
    {
        public int Book_ID { get; set; }

        [Required(ErrorMessage = "Book ko nam lekhnus")]
        [Display(Name ="Book Name")]
        public string Book_Title { get; set; }
        [Required(ErrorMessage = "Book ko barey ma short description dinus")]
        [Display(Name = "Description")]
        public string Book_Description { get; set; }
        [Required(ErrorMessage = "Price lekhnus")]
        public double Price { get; set; }
        
        public int Author_ID { get; set; }

        public virtual authordata authordata { get; set; }
    }
}
